Bug 1861026: update boot images to perform other rpm-ostree operations after OS rebase
openshift/installer pull request #4125
Opened 2020-09-02 14:29 UTC by sinnykumari

This fixes the issues which we have today during cluster install
involving multiple rpm-ostree operations such as both OS rebase and
rt-kernel switch.
PR https://github.com/openshift/machine-config-operator/pull/2029 fixes
the issue for day2 and we need to update boot images to include
machine-config-daemon containing the fixes for day1.

boot images update contains machine-config-daemon-4.5.0-202008280032.p0.git.2558.a93c8dc.el8
which contains the necessary fixes.

Used:

$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.5/45.82.202008280129-0/x86_64/meta.json amd64

2020-09-02 14:32 UTC, sinnykumari commented
/bugzilla refresh

2020-09-02 14:34 UTC, sinnykumari commented
/cc @runcom @cgwalters @miabbott @ashcrow

2020-09-02 16:45 UTC, sohankunkerkar commented
Is this a blocker for verifying https://bugzilla.redhat.com/show_bug.cgi?id=1861026?

2020-09-02 16:51 UTC, sinnykumari commented
yeah, since this will cover verifying the issue during day1 as well.

2020-09-02 17:01 UTC, sinnykumari commented
/bugzilla refresh

2020-09-02 17:07 UTC, cgwalters commented
Hmm.  I agree updating the bootimages is probably a good idea for this.  But strictly speaking I don't think we need to do so to verify the BZ - we can reproduce starting from 4.4.4 and upgrade.

2020-09-02 17:12 UTC, sinnykumari commented
right. With this PR we can also verify that day1 kernel-rt install works as expected (https://bugzilla.redhat.com/show_bug.cgi?id=1873383#c1)

2020-09-02 17:20 UTC, miabbott commented
@sinnykumari Updating the boot images as part of a z-stream release is something we only want to do sparingly.  Since the day 2 operation is fixed in 4.5 and users could use that, do you think it is necessary to pursue this PR?

2020-09-02 17:25 UTC, sinnykumari commented
I am not sure about that impact to users, will defer the decision to @ashcrow .

2020-09-03 15:05 UTC, cgwalters requested changes
*Slightly* leaning to defer this but if we gather a stronger argument why we need this then I'm OK with doing it.

2020-09-03 20:35 UTC, ashcrow commented
I'll break the tie :smile: Let's defer the bump. If we have something more urgent that needs a boot image bump in the future this fix will hop on as well.

2020-09-04 05:18 UTC, sinnykumari commented
thanks Colin and Steve for your input, definitely we can do the bootimage bump in future if it is important.

2020-09-04 05:18 UTC, closed without merging