Bug 1888378: [Azure][Destroy] Check if resource group exists
openshift/installer pull request #4320
Opened 2020-10-28 17:21 UTC by suhanime

Azure clubs all resources for a cluster within a resource group. The
pattern for delete is to first delete all the resources and then delete
the resource group.

However, when attempting delete, we should first check if the
resource group exists and then try to delete the resources. This is to
ensure delete exits gracefully when resource group wasn't created and/or
deleted before attempting delete.

2020-10-28 18:49 UTC, jhixson74 requested changes

2020-10-28 18:49 UTC, jhixson74 commented on pkg/destroy/azure/azure.go
> +			return nil
This should probably return err, other than that, LGTM.

2020-10-28 18:59 UTC, jhixson74 commented
/approve
/lgtm

2020-10-28 19:17 UTC, abhinavdahiya commented
Don't check for existence of a resource group and decide if any delete need to happen.

There are ans can be resources in other resource groups that need to be cleaned up, like the aad applications. 

Check for no work needed to be done in the error message. For example if we try to delete a resource group and it returns does not exist, treat that error as success.

/hold

2020-10-28 19:18 UTC, merged

2020-10-29 22:52 UTC, suhanime commented
> Don't check for existence of a resource group and decide if any delete need to happen.
> 
> There are ans can be resources in other resource groups that need to be cleaned up, like the aad applications.
> 
> Check for no work needed to be done in the error message. For example if we try to delete a resource group and it returns does not exist, treat that error as success.
> 
> /hold

You make a good point.
The current code is trying to delete the public records (like dns zones) first before deleting the resource group. The error in the bug can be traced to when the code tries to list the resources within the resource group, making the assumption that it already exists. To not break the logic, I have moved the code to "deletePublicRecords" func. Code is set to return if it cannot find a resource group simply because the rest of the logic in the method depends upon its existence.