Document how to deploy cluster with BM and VM workers
openshift/installer pull request #4336
Opened 2020-11-03 07:19 UTC by adduarte

2020-11-03 14:46 UTC, EmilienM commented on docs/user/openstack/deploy_baremetal_workers.md
> +deploying-cluster-with-mixture-of-vm-and-bm-workers
I don't think you need that line.

2020-11-03 14:48 UTC, EmilienM requested changes
One leftover, see inline

2020-11-04 08:18 UTC, adduarte commented on docs/user/openstack/deploy_baremetal_workers.md
> +deploying-cluster-with-mixture-of-vm-and-bm-workers
no I don't

2020-11-04 10:15 UTC, pierreprinetti commented
/approve
/lgtm
:+1:

2020-11-04 10:16 UTC, pierreprinetti commented
/hold
Please add a reference to a BZ or Jira card so that the change doesn't escape QE and dowstream-docs

2020-11-04 10:17 UTC, pierreprinetti commented
/label platform/openstack

2020-11-04 10:19 UTC, merged