Bug 1899853: openstack: CP nodes port to use addtional SGs
openshift/installer pull request #4411
Opened 2020-11-24 12:06 UTC by pierreprinetti

Assign the user-defined additional security groups to the Control Plane
port.

Fixes [Bug 1899853](https://bugzilla.redhat.com/show_bug.cgi?id=1899853)

2020-11-24 12:11 UTC, pierreprinetti commented
/label platform/openstack

2020-11-24 14:38 UTC, EmilienM commented
/lgtm

2020-11-24 14:45 UTC, Fedosin requested changes
Your patch leads to sg duplication here https://github.com/openshift/installer/blob/master/data/data/openstack/main.tf#L55-L58 because sgs from `topology` already contain `openstack_master_extra_sg_ids`

2020-11-24 15:22 UTC, pierreprinetti commented
As far as I can tell, `module.topology.master_sg_id` comes from the [output](https://github.com/openshift/installer/blob/5ce7e599e68ece532f2d52ec2b37edf75b2b5b6f/data/data/openstack/topology/outputs.tf#L2) of the [stock SG creation](https://github.com/openshift/installer/blob/5ce7e599e68ece532f2d52ec2b37edf75b2b5b6f/data/data/openstack/topology/sg-master.tf#L1-L4) only.

So if I'm correct, there's no duplication. @Fedosin can you please check and possibly disprove me please?

2020-11-24 15:30 UTC, mandre commented
It looks like we also need to add extra security groups to `api_port` and `ingress_port`, isn't it?

2020-11-24 15:40 UTC, mandre commented
> As far as I can tell, `module.topology.master_sg_id` comes from the [output](https://github.com/openshift/installer/blob/5ce7e599e68ece532f2d52ec2b37edf75b2b5b6f/data/data/openstack/topology/outputs.tf#L2) of the [stock SG creation](https://github.com/openshift/installer/blob/5ce7e599e68ece532f2d52ec2b37edf75b2b5b6f/data/data/openstack/topology/sg-master.tf#L1-L4) only.
> 
> So if I'm correct, there's no duplication... however my Terraform is still a bit uncertain!
> 
> @Fedosin can you please check and possibly disprove me please?

[master_sg_ids](https://github.com/openshift/installer/blob/master/data/data/openstack/main.tf#L55-L58) is only used in the `master` module creating the instances, and not in the `topology` one creating the ports on the subnets.
We should pass the same `master_sg_ids` variable in the `topology` module, and I think also a `worker_sg_ids` one for the `ingress_port`.

2020-11-25 07:29 UTC, mandre approved these changes
/approve
/lgtm

The patch fixes exactly the issue that is reported in the BZ so I do not see any reason not to approve. It would be nice to know if we also need to apply the additional security groups to the VIP ports. Otherwise what is the point of adding security groups at all to `api_port` and `ingress_port`?

2020-11-25 15:27 UTC, merged

2020-11-25 21:42 UTC, pierreprinetti commented
/cherry-pick release-4.6