Bug 1948359: aws: add permissions for untagging shared byo instance roles
openshift/installer pull request #4859
Opened 2021-04-19 15:58 UTC by staebler

Add checks to the Platform Permissions Check asset to verify that the user has the necessary permissions to remove the shared tag from the IAM roles that the user is supplying.

2021-04-21 15:32 UTC, mtnbikenc commented
/bugzilla refresh

2021-04-21 15:34 UTC, mtnbikenc approved these changes
/lgtm

2021-04-21 15:35 UTC, mtnbikenc commented
/retest

2021-04-21 15:39 UTC, staebler commented
/approve

2021-04-21 15:46 UTC, mtnbikenc commented on pkg/asset/installconfig/aws/permissions.go
> +	PermissionDeleteSharedRoles: {
`PermissionDeleteSharedInstanceRoles`?

2021-04-21 19:31 UTC, mtnbikenc requested changes
/lgtm cancel

2021-04-22 18:53 UTC, staebler commented on pkg/asset/installconfig/aws/permissions.go
> +	PermissionDeleteSharedRoles: {
Fixed.

2021-04-23 18:33 UTC, mtnbikenc commented
/lgtm

2021-04-23 18:34 UTC, mtnbikenc approved these changes

2021-04-24 13:58 UTC, merged