Bug 1957809: Validation of platform.openstack.machineSubnet
openshift/installer pull request #4917
Opened 2021-05-08 03:11 UTC by adduarte

If the user provides an UUID under platform.openstack.machinesSubnet
of a subnet which does not exist, the installer should not fail with a
backtrace.
Instead, the installer should exit gracefully and provide the correct error
to the user.

2021-05-08 08:24 UTC, Fedosin requested changes
Just one suggestion. And also it would be nice to have a unit test for this case.

2021-05-08 08:24 UTC, Fedosin commented on pkg/asset/installconfig/openstack/validation/platform.go
> +		if !validUUIDv4(p.MachinesSubnet) || ci.MachinesSubnet == nil {
I think we need to differentiate this errors. If there is no machine subnet with provided id, then we should generate NotFound error.
```go
if !validUUIDv4(p.MachinesSubnet) {
	allErrs = append(allErrs, field.InternalError(fldPath.Child("machinesSubnet"), errors.New("invalid subnet ID")))
} else if ci.MachinesSubnet == nil {
	allErrs = append(allErrs, field.NotFound(fldPath.Child("machinesSubnet"), p.MachinesSubnet))
} else if n.MachineNetwork[0].CIDR.String() != ci.MachinesSubnet.CIDR {
	allErrs = append(allErrs, field.InternalError(fldPath.Child("machinesSubnet"), fmt.Errorf("the first CIDR in machineNetwork, %s, doesn't match the CIDR of the machineSubnet, %s", n.MachineNetwork[0].CIDR.String(), ci.MachinesSubnet.CIDR)))
}
```

2021-05-08 08:32 UTC, mandre commented on pkg/asset/installconfig/openstack/validation/platform.go
> +		if !validUUIDv4(p.MachinesSubnet) || ci.MachinesSubnet == nil {
We should rather use the `field.NotFound` error for consistency:
```suggestion
		if ci.MachinesSubnet == nil {
			allErrs = append(allErrs, field.NotFound(fldPath.Child("machinesSubnet"), p.MachinesSubnet))
		}
		if !validUUIDv4(p.MachinesSubnet) {
```

2021-05-10 07:20 UTC, mandre commented
/label platform/openstack

2021-05-11 07:47 UTC, mandre reviewed
/lgtm
/approve

2021-05-11 11:43 UTC, merged