ovirt: split terraform into stages
openshift/installer pull request #5079
Opened 2021-07-14 05:43 UTC by jhixson74

Split the terraform for the ovirt platform into stages.

image: upload the rhcos image to a temporary vm
cluster: create the permanent cluster resources
bootstrap: create the bootstrap resources

2021-07-14 06:03 UTC, janosdebugs requested changes
Looks good on the surface, but I think we are going to need a BZ for this, otherwise QE won't have it on their radar and it's a non-trivial change. @Gal-Zaidman WDYT?

2021-07-14 06:03 UTC, janosdebugs commented on data/data/ovirt/variables-ovirt.tf
> +variable "ovirt_base_image_name" {
Since  you are renaming this variable here, could you please consistently rename it everywhere?

2021-07-14 06:03 UTC, janosdebugs commented on pkg/tfvars/ovirt/ovirt.go
> +	BaseImageName           string                   `json:"ovirt_base_image_name,omitempty"`
See my comment above, please consistently rename it everywhere in the oVirt codebase.

2021-07-14 15:15 UTC, janosdebugs approved these changes
LGTM

2021-07-15 04:55 UTC, jhixson74 commented
/test e2e-ovirt

2021-07-15 06:38 UTC, jhixson74 commented
/retest

2021-07-19 14:37 UTC, patrickdillon commented
We should get rid of these warnings by including declarations for these input variables:

```
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="Warning: Value for undeclared variable"
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="The root module does not declare a variable named \"tmp_import_vm_id\" but a"
time="2021-07-15T07:18:39Z" level=debug msg="value was found in file"
time="2021-07-15T07:18:39Z" level=debug msg="\"/tmp/openshift-install-image-792920205/image.tfvars.json\". To use this value,"
time="2021-07-15T07:18:39Z" level=debug msg="add a \"variable\" block to the configuration."
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="Using a variables file to set an undeclared variable is deprecated and will"
time="2021-07-15T07:18:39Z" level=debug msg="become an error in a future release. If you wish to provide certain \"global\""
time="2021-07-15T07:18:39Z" level=debug msg="settings to all configurations in your organization, use TF_VAR_..."
time="2021-07-15T07:18:39Z" level=debug msg="environment variables to set these instead."
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="Warning: Value for undeclared variable"
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="The root module does not declare a variable named \"release_image_template_id\""
time="2021-07-15T07:18:39Z" level=debug msg="but a value was found in file"
time="2021-07-15T07:18:39Z" level=debug msg="\"/tmp/openshift-install-image-792920205/cluster.tfvars.json\". To use this"
time="2021-07-15T07:18:39Z" level=debug msg="value, add a \"variable\" block to the configuration."
time="2021-07-15T07:18:39Z" level=debug
time="2021-07-15T07:18:39Z" level=debug msg="Using a variables file to set an undeclared variable is deprecated and will"
time="2021-07-15T07:18:39Z" level=debug msg="become an error in a future release. If you wish to provide certain \"global\""
time="2021-07-15T07:18:39Z" level=debug msg="settings to all configurations in your organization, use TF_VAR_..."
time="2021-07-15T07:18:39Z" level=debug msg="environment variables to set these instead."
time="2021-07-15T07:18:39Z" level=debug
```

2021-07-22 11:53 UTC, Gal-Zaidman commented
/hold

2021-09-15 21:35 UTC, jhixson74 commented
/test e2e-ovirt

2021-09-21 22:41 UTC, jhixson74 commented
/test e2e-ovirt

2021-09-29 07:15 UTC, Gal-Zaidman commented
/retest

2021-10-17 08:09 UTC, Gal-Zaidman commented
On 4.10 we are planning a very big change to the oVirt terraform provider which will basically require porting the current logic to the new form - therefore I see no need to invest in the split effort now, but just keep it in mind when we will refactor the existing tf code to the new form.
I think we can close this PR @janosdebugs  what do you think? should it be kept open as a knowledge source?

2021-10-17 08:12 UTC, janosdebugs commented
Yes, let's keep this PR as a knowledge source.

2021-10-20 22:05 UTC, janosdebugs commented
@jhixson74 could you leave it open for the time being please? We'll ping once we have ported the efforts to the new TF provider.

2021-10-22 04:01 UTC, staebler commented
> On 4.10 we are planning a very big change to the oVirt terraform provider which will basically require porting the current logic to the new form - therefore I see no need to invest in the split effort now, but just keep it in mind when we will refactor the existing tf code to the new form. I think we can close this PR @janosdebugs what do you think? should it be kept open as a knowledge source?

@Gal-Zaidman Do you have a rough estimate for when you think your changes would be ready? These tf stage PRs are blocking our bump of the terraform version that we use (hence the impetus to use stages to begin with). I am wondering, given that the majority of the work is already done for this splitting, whether we can land these changes in the interim. As far as I know, the only work outstanding for this PR is to fix up the IP extraction for bootstrap gathering.

2021-10-22 04:55 UTC, janosdebugs commented
@staebler if it's blocking you then let's by all means do it, we still need a few weeks to complete our work as we are targeting feature freeze with our changes.

2021-12-13 14:24 UTC, staebler commented
Closing this in favor of https://github.com/openshift/installer/pull/5034. The other PR has been rebased and has a fix for the bootstrap gather.
/close

2021-12-13 14:28 UTC, closed without merging