PowerVS: Add zones
openshift/installer pull request #5238
Opened 2021-09-23 20:51 UTC by mjturek

2021-09-29 19:49 UTC, clnperez requested changes
a couple more requests i missed before

2021-09-29 19:49 UTC, clnperez commented on pkg/tfvars/powervs/powervs.go
> +	VPCZone              string `json:"powervs_vpx_zone"`
there's a typo here (x instead of c)

2021-09-29 19:49 UTC, clnperez commented on pkg/rhcos/powervs_regions.go
> +// PowerVSRegion describes resources associated with a region in powervs.
This comment should end with "Power VS" instead of "powervs"

2021-09-29 19:49 UTC, clnperez commented on pkg/rhcos/powervs_regions.go
>  // TODO(cklokman): This entire file should be programatically generated similar to aws
can you delete this while you're editing this file?

2021-10-05 17:30 UTC, mjturek commented
This PR was pulled into #5224 with the changes requested by @clnperez . Closing.

2021-10-05 17:30 UTC, closed without merging