Bug 2020480: Update govmomi
openshift/installer pull request #5495
Opened 2021-12-16 23:45 UTC by ayesha54

Updating the version of govmomi to fix the bugs we are experiencing in terms of failing tests for the CI jobs.

Attaching some useful links below:

https://github.com/openshift/release/blob/master/ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-commands.sh#L38-L44

https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L59-L61

https://github.com/vmware/govmomi/pull/1916/files

2021-12-16 23:48 UTC, ayesha54 commented
/bugzilla refresh

2021-12-16 23:53 UTC, ayesha54 commented
/bugzilla refresh

2021-12-16 23:57 UTC, ayesha54 commented
/bugzilla refresh

2021-12-16 23:59 UTC, ayesha54 commented
/bugzilla refresh

2021-12-17 00:04 UTC, ayesha54 commented
/retest

2021-12-17 00:18 UTC, kirankt requested changes

2021-12-17 00:18 UTC, kirankt commented on go.mod
> -	cloud.google.com/go/bigtable v1.5.0 // indirect
Removing these modules does not look right. Please re-run verify vendor.

2021-12-17 01:13 UTC, ayesha54 commented
@jcpowermac

2021-12-17 02:26 UTC, staebler reviewed
Changes seem fine to me.
Need to re-run `go mod vendor`.
/approve

2021-12-17 02:26 UTC, staebler commented
/bugzilla refresh

2021-12-17 04:14 UTC, jcpowermac reviewed
I don't see a change to the dockerfile. The govc binary in the container is very out of date and was our guess to the cause of the problem.

2021-12-18 16:40 UTC, ayesha54 commented
> Changes seem fine to me. Need to re-run `go mod vendor`. /approve

I have ran the go mod vendor but didn't pushed the untracked files.

2022-01-04 14:12 UTC, staebler commented
> I don't see a change to the dockerfile. The govc binary in the container is very out of date and was our guess to the cause of the problem.

Can you elaborate on this? Do you think that it is *both* the govmomi module and the govc binary that need to be updated? Or do you think that it is *only* the govc binary that needs to be updated? Can you provide more details about the root cause?

2022-01-05 18:14 UTC, jcpowermac commented
/test e2e-vsphere-upi

2022-01-05 18:15 UTC, jcpowermac commented
This is the change I was expecting.
/lgtm

2022-01-05 18:19 UTC, ayesha54 commented
> > I don't see a change to the dockerfile. The govc binary in the container is very out of date and was our guess to the cause of the problem.
> 
> Can you elaborate on this? Do you think that it is _both_ the govmomi module and the govc binary that need to be updated? Or do you think that it is _only_ the govc binary that needs to be updated? Can you provide more details about the root cause?

@staebler your comment is definitely helpful, so for now I am upgrading the govc at the container level, as we are guessing that, since its a very old version of govc that can be the cause of the failing jobs with that error but we really don't know, once the PR is merge, I can see the CI jobs results.

2022-01-05 18:37 UTC, staebler commented
I am fine with putting this in as an initial step. But the BZ report was that this occurred for manual installations as well, which presumably were not using the UPI CI image.

2022-01-05 18:55 UTC, jcpowermac commented
> I am fine with putting this in as an initial step. But the BZ report was that this occurred for manual installations as well, which presumably were not using the UPI CI image.

Right, this change is more to validate a guess that its related to a bug with govmomi (and govc). If this resolve the issue we were seeing with UPI and the OVA import we can move on to the terraform provider.

https://github.com/vmware/govmomi/issues/1908

2022-01-05 19:34 UTC, jcpowermac commented
@ayesha54 govc is now in a tar.gz

https://github.com/vmware/govmomi/releases

2022-01-06 14:22 UTC, jcpowermac commented
/test e2e-vsphere-upi

2022-01-06 15:18 UTC, jcpowermac commented
@ayesha54 something isn't quite right
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/5495/pull-ci-openshift-installer-master-e2e-vsphere-upi/1479096065838813184#1:build-log.txt%3A55

2022-01-06 19:49 UTC, ayesha54 commented
/test e2e-vsphere-upi

2022-01-07 13:52 UTC, ayesha54 commented
/test e2e-vsphere-upi

2022-01-07 13:55 UTC, jcpowermac commented
Reviewed vsphere-upi installation was fine, test failure unrelated

/lgtm

2022-01-07 17:07 UTC, merged

2022-01-10 14:57 UTC, ayesha54 commented
/cherry-pick release-4.9

2022-01-10 14:57 UTC, ayesha54 commented
/cherry-pick release-4.8

2022-01-10 14:57 UTC, ayesha54 commented
/cherry-pick release-4.7

2022-01-10 14:57 UTC, ayesha54 commented
/cherry-pick release-4.6