Changed Lower limits of CPU for PowerVS Cloud
openshift/installer pull request #5929
Opened 2022-05-19 11:52 UTC by bkhadars

1. Changed Lower limit of CPU
2. Fixes the comment from the PR 5609: https://github.com/openshift/installer/pull/5609/files#r814418626

2022-05-19 12:43 UTC, bkhadars commented
/cc @clnperez

2022-05-24 10:54 UTC, bkhadars commented
/cc @Prashanth684 @mkumatag @clnperez PTAL

2022-05-24 10:54 UTC, bkhadars commented
/cc @Prashanth684 @mkumatag @clnperez PTAL

2022-05-25 07:37 UTC, mkumatag requested changes

2022-05-26 11:38 UTC, bkhadars commented on pkg/types/powervs/validation/machinepool.go
> +			exp := `(\b^[0]?[.](5|50|75)$\b)|(\b^([1-9]|[12][0-9]|3[0-1])[.]?(25|5|50|75)?$\b)|(\b^32$\b)`
updated with coment

2022-05-26 11:49 UTC, mkumatag commented on pkg/types/powervs/validation/machinepool.go
> +			exp := `(\b^[0]?[.](5|50|75)$\b)|(\b^([1-9]|[12][0-9]|3[0-1])[.]?(25|5|50|75)?$\b)|(\b^32$\b)`
why we are restricting to 32 only? there are different possible numbers based on the system type you choose, for more information - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server

2022-05-31 16:26 UTC, clnperez requested changes

2022-06-10 20:11 UTC, clnperez commented
@bkhadars can you add WIP to the title of this one until you've gotten the upper bounds checking done? and change the title to reflect its new purpose. thanks!

2022-06-14 14:37 UTC, clnperez commented
n/m. it sounds like this PR will not be majorly reworked, and we'll just add the lower limts. still needs a rebase though @bkhadars

2022-06-15 09:23 UTC, bkhadars commented on pkg/types/powervs/validation/machinepool.go
> +			exp := `(\b^[0]?[.](5|50|75)$\b)|(\b^([1-9]|[12][0-9]|3[0-1])[.]?(25|5|50|75)?$\b)|(\b^32$\b)`
@mkumatag verifying upper limit will be reworked in the new PR

2022-06-15 09:28 UTC, bkhadars commented
/bugzilla refresh

2022-06-16 18:50 UTC, jhixson74 commented
/approve

2022-06-16 21:48 UTC, merged