Bug 2061947: IBMCloud: Skip DNS Record delete
openshift/installer pull request #6013
Opened 2022-06-15 19:44 UTC by cjschaef

During uninstall/destroy, if no CIS CRN is available, the installer
errors trying to collect DNS Records for deletion. If no CIS CRN
is supplied in metadata, skip attempting to delete the DNS Records.

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061947

2022-06-15 19:45 UTC, cjschaef commented
With patch and empty `cisInstanceCRN` in metadata
```
# cat bz_2061947_clusters/bz-2061947-c6/metadata.json 
{"clusterName":"bz-2061947-c6","clusterID":"foo","infraID":"bz-2061947-c6-prkfx","ibmcloud":{"accountID":"foo","baseDomain":"ocp.cjschaef.com","cisInstanceCRN":"","region":"eu-gb","resourceGroupName":"bz-2061947-c6-prkfx"}}

# go/src/github.com/openshift/installer/bin/openshift-install destroy cluster --dir bz_2061947_clusters/bz-2061947-c6
INFO Stopped instance "bz-2061947-c6-prkfx-worker-2-9ht5d" 
...
INFO Skipping deletion of DNS Records, no CIS CRN found 
INFO Deleted COS instance "bz-2061947-c6-prkfx-image-registry" 
INFO Deleted COS instance "bz-2061947-c6-prkfx-cos" 
INFO Deleted resource group "bz-2061947-c6-prkfx" 
INFO Time elapsed: 5m41s
```

2022-06-16 07:20 UTC, MayXuQQ commented
pre-merge build [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1537289692242776064)

2022-06-20 08:25 UTC, MayXuQQ commented
pre-merge test: [registry.build05.ci.openshift.org/ci-ln-kgmc6xb/release:latest](https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1537823013293002752/build-log.txt)
destried the cluster newugd-14826-tgtrz
still can list the subnets:
$ ibmcloud resource search "name: newugd-14826-tgtrz*" |  grep -E "Name|Type"
Name:                newugd-14826-tgtrz-subnet-compute-us-east-1   
Resource Type:       subnet   
Name:                newugd-14826-tgtrz-subnet-control-plane-us-east-1   
Resource Type:       subnet   
Name:                newugd-14826-tgtrz-subnet-compute-us-east-3   
Resource Type:       subnet

2022-06-20 09:32 UTC, MayXuQQ requested changes
subnets fail to be deleted.

2022-06-21 14:11 UTC, cjschaef commented
@MayXuQQ 
I performed additional testing, and I think the [subnet failure above](https://github.com/openshift/installer/pull/6013#issuecomment-1160132092) is unrelated, and caused by the known issue of [orphaned service-instances for IBM Cloud resources](https://bugzilla.redhat.com/show_bug.cgi?id=2092975) instead.

I was able to confirm after 2 clean cluster creations, that all resources were properly deleted, except the DNS Records, when I manually removed the CIS CRN from the `metadata.json` prior to cluster destroy.
```
# cat bz_2061947_clusters/bz-2061947-c8/metadata.json 
{"clusterName":"bz-2061947-c8","clusterID":"7c200d3d-d7fc-49d9-9808-b539a407f062","infraID":"bz-2061947-c8-9r42t","ibmcloud":{"accountID":"foo","baseDomain":"ocp.cjschaef.com","cisInstanceCRN":"","region":"us-east","resourceGroupName":"bz-2061947-c8-9r42t"}}

# go/src/github.com/openshift/installer/bin/openshift-install destroy cluster --dir bz_2061947_clusters/bz-2061947-c8
INFO Stopped instance "bz-2061947-c8-9r42t-bootstrap"
...
INFO Deleted floating IP "bz-2061947-c8-9r42t-bootstrap-node-ip" 
INFO Deleted VPC "bz-2061947-c8-9r42t-vpc"        
INFO Skipping deletion of DNS Records, no CIS CRN found 
INFO Deleted resource group "bz-2061947-c8-9r42t" 
INFO Deleted COS instance "bz-2061947-c8-9r42t-cos" 
INFO Deleted COS instance "bz-2061947-c8-9r42t-image-registry" 
INFO Time elapsed: 6m8s
```

```
# ic resource search "name: bz-2061947-c8-9r42t"
No resources found
```

2022-06-21 14:13 UTC, cjschaef commented
The `e2e-ibmcloud` test is expected to fail, since we still have yet to take the time to go through the OCP Conformance results to resolve all of the failing tests, to get a successful result, and fully "enable" the e2e testing for IBM Cloud (GA requirements have taken priority to this point).

2022-06-21 16:26 UTC, MayXuQQ approved these changes
pre-merge test ok

2022-06-30 16:37 UTC, patrickdillon commented
/approve
/lgtm

2022-07-01 15:04 UTC, patrickdillon commented
/skip

2022-07-01 18:58 UTC, jeffnowicki commented
/retest-required

2022-07-06 13:42 UTC, patrickdillon commented
/hold cancel

2022-07-11 14:06 UTC, patrickdillon commented
/hold cancel

2022-07-11 16:55 UTC, patrickdillon commented
/retest
/skip

2022-07-11 18:22 UTC, jeffnowicki commented
/retest-required

2022-07-12 00:09 UTC, jeffnowicki commented
/skip
/retest-required

2022-07-12 10:46 UTC, patrickdillon commented
/override ci/prow/e2e-aws

2022-07-12 10:53 UTC, merged