Bug 2082395: Make azure baseDomainResoureGroup optional for private c…
openshift/installer pull request #6049
Opened 2022-06-27 16:52 UTC by AnnaZivkovic

…lusters

A private azure IPI cluster does not require any public base domain. If a base domain was not provided Terraform would through an error and the installation would fail. By removing omitempty the BaseDomainResourceGroupName becomes optional.

2022-06-27 19:38 UTC, AnnaZivkovic commented
/bugzilla refresh

2022-06-28 12:19 UTC, AnnaZivkovic commented
/bugzilla refresh

2022-06-28 12:22 UTC, AnnaZivkovic commented
/bugzilla refresh

2022-06-29 10:36 UTC, MayXuQQ commented
pre-merge check with registry.build05.ci.openshift.org/ci-ln-drn5b3t/release:latest
- private cluster without 'baseDomainResoureGroup'  PASS
- public cluster, must has 'baseDomainResoureGroup'

- > ./openshift-install explain installconfig.platform.azure.baseDomainResourceGroupName
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <string>
  BaseDomainResourceGroupName specifies the resource group where the Azure DNS zone for the base domain is found.

2022-06-29 10:38 UTC, MayXuQQ commented
/label qe-approved
/bugzilla cc-qa

2022-06-29 11:17 UTC, MayXuQQ approved these changes
whether need change the the explain ?
> ./openshift-install explain installconfig.platform.azure.baseDomainResourceGroupName
> KIND: InstallConfig
> VERSION: v1
> 
> RESOURCE:
> BaseDomainResourceGroupName specifies the resource group where the Azure DNS zone for the base domain is found.

2022-06-29 17:05 UTC, MayXuQQ commented
/remove-label qe-approved

2022-06-29 17:51 UTC, jhixson74 requested changes

2022-06-29 17:51 UTC, jhixson74 commented on pkg/types/azure/platform.go
>  	BaseDomainResourceGroupName string `json:"baseDomainResourceGroupName,omitempty"`
You could probably write an explanation why this is parameter is optional and under what circumstances it should be set/not set.

2022-06-30 09:41 UTC, MayXuQQ commented
ref https://github.com/openshift/installer/pull/5802#issuecomment-1097430220
You need to include [the generated code ](https://github.com/openshift/installer/blob/master/docs/dev/explain.md#generating-the-documentation)in your commit as well. That is why the verify-codegen test is failing.You need to include [the generated code ](https://github.com/openshift/installer/blob/master/docs/dev/explain.md#generating-the-documentation)in your commit as well. That is why the verify-codegen test is failing.You need to include [the generated code ](https://github.com/openshift/installer/blob/master/docs/dev/explain.md#generating-the-documentation)in your commit as well. That is why the verify-codegen test is failing.

2022-07-01 07:38 UTC, MayXuQQ commented
pre-merge checked with registry.build05.ci.openshift.org/ci-ln-x8q8qlk/release:latest

> ./openshift-install explain installconfig.platform.azure.baseDomainResourceGroupName
> KIND:     InstallConfig
> VERSION:  v1
> 
> RESOURCE: <string>
>   BaseDomainResourceGroupName specifies the resource group where the Azure DNS zone for the base domain is found. This field is optional when creating a private cluster, otherwise required.
>

2022-07-05 21:36 UTC, patrickdillon commented
/approve

The unit tests are failing because the tests here: https://github.com/openshift/installer/blob/master/pkg/explain/printer_test.go need to be updated. These tests are problematic in that way...

2022-07-10 20:54 UTC, patrickdillon commented
/lgtm

2022-07-11 07:33 UTC, merged

2022-07-14 12:57 UTC, patrickdillon commented
/cherry-pick release-4.10