openstack: Update base images
openshift/installer pull request #6082
Opened 2022-07-05 15:05 UTC by pierreprinetti

2022-07-05 15:34 UTC, pierreprinetti commented
/cc mandre

2022-07-06 06:07 UTC, mandre reviewed
For some reason it's not using the `OpenStack Yoga Repository` you're providing, and it's still pulling openstack rpms from `openstack-16-for-rhel-8-rpms`. Not sure where that repo is coming from.
Interestingly, the `rdo-train` repo wasn't used at all. From [a different CI job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/6083/pull-ci-openshift-installer-master-images/1544507474105602048/artifacts/build-logs/openstack-installer.log):
```
2022-07-06T03:01:59.568022776Z Errors during downloading metadata for repository 'openstack-train':
2022-07-06T03:01:59.568022776Z   - Status code: 404 for http://mirror.centos.org/centos/8/cloud/x86_64/openstack-train/repodata/repomd.xml (IP: 67.220.193.10)
2022-07-06T03:01:59.568022776Z Error: Failed to download metadata for repo 'openstack-train': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

2022-07-06 15:20 UTC, dulek requested changes

2022-07-06 19:09 UTC, pierreprinetti commented
/retest

2022-07-07 05:31 UTC, mandre commented on images/openstack/Dockerfile.ci
> +FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11 AS builder
registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12 is available now, shouldn't we use it?

2022-07-07 05:46 UTC, mandre reviewed
/lgtm
/approve
/hold for CI

2022-07-07 20:23 UTC, pierreprinetti commented
/hold cancel

2022-07-08 01:17 UTC, merged