Bug 2084471: validate baremetal hosts names are lowercase RFC 1123
openshift/installer pull request #6112
Opened 2022-07-12 13:55 UTC by tdomnesc

Capital letters in install-config.yaml .platform.baremetal.hosts[].name caused bootkube to loop forever with errors.
The install gets stuck on openshift-master-host creation.
See: https://bugzilla.redhat.com/show_bug.cgi?id=2084471

This patch uses the same validation function and makes the install fail early with a clear message.

2022-07-13 12:06 UTC, elfosardo commented
/retest

2022-07-13 12:15 UTC, elfosardo requested changes
this probably needs an update to the unit tests

2022-07-15 08:46 UTC, tdomnesc commented
/bugzilla refresh
/retest

2022-07-20 07:24 UTC, tdomnesc commented
/retest

2022-07-21 07:10 UTC, tdomnesc commented
/retest

2022-07-22 08:06 UTC, tdomnesc commented
/retest

2022-07-25 17:46 UTC, sadasu commented
/retest

2022-07-25 17:47 UTC, sadasu commented
/approve

2022-07-26 08:35 UTC, tdomnesc commented
/retest

2022-07-27 07:34 UTC, tdomnesc commented
/retest

2022-07-27 11:31 UTC, tdomnesc commented
/retest

2022-07-29 11:13 UTC, tdomnesc commented
/retest

2022-08-01 07:38 UTC, tdomnesc commented
/retest

2022-08-01 15:24 UTC, tdomnesc commented
/retest

2022-08-03 07:44 UTC, elfosardo requested changes

2022-08-04 14:12 UTC, elfosardo commented
/retest

2022-08-04 14:12 UTC, elfosardo commented
/lgtm
looks great, thanks

2022-08-05 06:36 UTC, tdomnesc commented
/retest

2022-08-05 13:58 UTC, tdomnesc commented
/retest

2022-08-08 09:19 UTC, elfosardo commented
/retest

2022-08-08 09:19 UTC, elfosardo commented
/unhold

2022-08-08 13:19 UTC, elfosardo commented
/test e2e-metal-ipi-ovn-ipv6

2022-08-08 13:19 UTC, elfosardo commented
/test e2e-metal-ipi

2022-08-09 09:08 UTC, elfosardo commented
/retest

2022-08-09 13:13 UTC, elfosardo commented
/retest

2022-08-10 06:48 UTC, elfosardo commented
/retest
/unhold

2022-08-11 07:03 UTC, tdomnesc commented
/retest

2022-08-11 10:14 UTC, tdomnesc commented
/retest

2022-08-16 09:29 UTC, tdomnesc commented
/retest
/unhold

2022-08-23 13:39 UTC, derekhiggins commented
/test e2e-metal-ipi-ovn-ipv6

2022-08-24 11:28 UTC, derekhiggins commented
/test e2e-metal-ipi-ovn-ipv6

It looks like the reason this is failing is because the client can't connect to the kube  api , going to try and look at this environment while its running to find the problem

2022-08-24 13:20 UTC, derekhiggins commented
/test e2e-metal-ipi-ovn-ipv6

last one failed for a new reason

2022-08-24 13:50 UTC, elfosardo commented
/unhold

2022-08-25 08:03 UTC, derekhiggins commented
/unhold

> last one failed for a new reason

I didn't mean it was ready to be unheld, there is a problem with this job, investigating...

2022-08-25 08:04 UTC, derekhiggins commented
/hold

last one failed for a new reason

I didn't mean it was ready to be unheld, there is a problem with this job, investigating...

Merge

2022-08-30 13:47 UTC, tdomnesc commented
/retest

2022-09-01 10:33 UTC, tdomnesc commented
/retest

2022-09-05 07:43 UTC, tdomnesc commented
/retest

2022-09-05 11:59 UTC, tdomnesc commented
/unhold

2022-09-05 19:39 UTC, merged