Update power-go-client
openshift/installer pull request #6229
Opened 2022-08-15 21:52 UTC by 23TNC

Updating power-go-client to pick up bug fixes and making error messages clearer.

2022-08-16 11:48 UTC, r4f4 commented
Vendor changes should be in their own commit. See https://github.com/openshift/installer/blob/master/docs/dev/dependencies.md#go

2022-08-16 11:48 UTC, r4f4 commented
/ok-to-test

2022-08-24 16:22 UTC, sadasu commented
/test verify-vendor

2022-08-24 16:28 UTC, sadasu commented
/test e2e-ibmcloud

2022-08-25 17:20 UTC, clnperez commented
@sadasu i don't think we need to worry about getting the tests passing as @23TNC will be splitting this into two commits and they'll have to be re-run again. unless someone's changed their mind about that request

2022-08-25 17:26 UTC, r4f4 commented
/hold

2022-09-06 22:30 UTC, clnperez commented
@23TNC any update on this? the new version has some updates that would make debugging easier

2022-09-07 01:24 UTC, mjturek requested changes

2022-09-07 01:24 UTC, mjturek commented on go.sum
>  github.com/IBM-Cloud/power-go-client v1.1.5/go.mod h1:YcAHrWuTvckGQYPLLReJ9ijcO/tQuRxAp2kCZ7fnnVk=
These lines need to be removed.

2022-09-08 16:33 UTC, clnperez commented
/retest-required

2022-09-09 21:15 UTC, clnperez commented
@r4f4 can you remove the hold from this? it should be good to go now

2022-09-09 21:15 UTC, clnperez commented
/retest-required

2022-09-09 21:29 UTC, r4f4 commented
/hold cancel

2022-09-09 21:33 UTC, r4f4 commented
@23TNC would you mind rewording "go mod, and go sum" commit to something like:

```
ibmcloud: update power-go-client

The new version fixes bugs and has clearer error messages
```

2022-09-12 22:19 UTC, 23TNC commented
/retest-required

2022-09-13 01:51 UTC, 23TNC commented
/retest-required

2022-09-13 12:50 UTC, 23TNC commented
/retest-required

2022-09-14 19:18 UTC, 23TNC commented
/retest-required

2022-09-14 21:26 UTC, clnperez commented
@rna-afk can you help unstick this one too? the ci doesn't seem to be re-running the tests that failed, and if i click the old ones links from the table, it looks like they haven't run at all since the 9th. Maybe they've been renamed or removed?

2022-09-15 13:13 UTC, rna-afk commented
/retest

2022-09-15 13:15 UTC, mjturek commented
/lgtm

2022-09-15 16:07 UTC, 23TNC commented
/retest

2022-09-16 00:20 UTC, 23TNC commented
/retest-required

2022-09-19 13:45 UTC, clnperez commented
@rna-afk can you approve this one?

2022-09-19 13:54 UTC, rna-afk commented
/approve

2022-09-19 14:45 UTC, clnperez commented
since this one is a powervs-specific pr, is there any way we can skip all these flaky jobs if they continue to not pass and change names, etc.? we really want this one in

2022-09-19 14:53 UTC, rna-afk commented
I'll skip them if they fail

2022-09-19 20:11 UTC, rna-afk commented
/skip

2022-09-20 05:38 UTC, merged