WIP OCPBUGS-2881: Destroy the service and host project dns records
openshift/installer pull request #6534
Opened 2022-10-28 19:55 UTC by barbacbd

** Search the host and service projects for the DNS records that were created during the install (when using the a networkProjectID).

2022-12-15 19:22 UTC, barbacbd commented
/jira refresh

2022-12-15 19:22 UTC, barbacbd commented
/jira refresh

2022-12-15 20:28 UTC, barbacbd commented
/override ci/prow/golint

2022-12-16 05:35 UTC, jianli-wei requested changes
Please see my comment at [the bug](https://issues.redhat.com/browse/OCPBUGS-2881), thanks!

2022-12-16 13:45 UTC, barbacbd commented
@jianli-wei I commented back on the Jira bug. I think that your concerns have explanations. Also this PR is only meant to fix the destroy bug. Any other issues should be talked through or a bug would be opened.

2022-12-16 13:46 UTC, barbacbd commented
/override ci/prow/e2e-aws-ovn-disruptive
/override ci/prow/okd-e2e-aws-ovn-upgrade

2022-12-16 16:24 UTC, barbacbd commented
/skip

2022-12-16 17:08 UTC, barbacbd commented
/retest

2022-12-16 17:40 UTC, r4f4 reviewed
Some nitpick comments but overall looks good.
/lgtm

2022-12-16 17:40 UTC, r4f4 commented on pkg/destroy/gcp/dns.go
> +	possibleParentZones := []*dnsZone{}
Nit: This name is very close to `possibleZoneParents`. Since you're checking in the loop below, can this just be `parentZones`?

2022-12-16 17:40 UTC, r4f4 commented on pkg/destroy/gcp/dns.go
> +				logger.Debugf("Found possible parent dns zone: %s", zone.name)
Nit: Is the `possible` qualifier here necessary? From what I understand, the zones returned are later used as if they *were* parent zones, not *maybe let's double-check*.

2022-12-19 15:30 UTC, r4f4 commented
/lgtm

2022-12-19 19:36 UTC, barbacbd commented
/skip

2022-12-20 13:44 UTC, barbacbd commented
/override ci/prow/e2e-aws-ovn

2022-12-20 13:50 UTC, barbacbd commented
/override ci/prow/e2e-agent-compact-ipv4

2023-01-05 07:22 UTC, r4f4 commented
/approve

2023-01-06 00:01 UTC, merged