AGENT-504: Agent extract binary
openshift/installer pull request #6777
Opened 2023-01-17 10:03 UTC by andfasano

This is a preliminary patch that refactors the `oc.go` code to introduce a new `ExtractFile` method in the `Release` interface.
This method will be required to extract the agent-tui binary from the release payload

2023-01-17 17:54 UTC, bfournie commented
Looks reasonable
/lgtm

2023-01-18 07:35 UTC, rwsu requested changes

2023-01-18 08:03 UTC, rwsu commented on pkg/asset/agent/image/oc.go
> +func (r *release) ExtractFile(image string, filename string, architecture string) (string, error) {
I think image is not needed too.

2023-01-18 08:03 UTC, rwsu commented on pkg/asset/agent/image/oc.go
> +	imagePullSpec, err := r.getImageFromRelease(image)
I had trouble using the function, but when I changed image to machineOsImageName here, the function worked. Does that sound right to you?
```suggestion
	imagePullSpec, err := r.getImageFromRelease(machineOsImageName)
```

2023-01-18 08:29 UTC, rwsu commented on pkg/asset/agent/image/oc.go
> +	imagePullSpec, err := r.getImageFromRelease(image)
Disregard this comment, as Andrea explained to me, the image parameter should be the name of an image as it is in the release image. The machineOsImageName is coincidentally one of the images in the payload.

2023-01-18 11:31 UTC, andfasano commented on pkg/asset/agent/image/oc.go
> +func (r *release) ExtractFile(image string, filename string, architecture string) (string, error) {
> The architecture string is unused.

Thanks for spotting the typo! Removed

2023-01-18 17:59 UTC, bfournie commented
/lgtm

2023-01-19 03:11 UTC, rwsu approved these changes

2023-01-19 13:56 UTC, merged