asset/installconfig/gcp: check GOOGLE_APPLICATION_CREDENTIALS env var
openshift/installer pull request #6863
Opened 2023-02-16 07:50 UTC by tosmi

according to
https://cloud.google.com/docs/authentication/provide-credentials-adc#local-key the default for application credentials is to set
GOOGLE_APPLICATION_CREDENTIALS. currently this var is missing from the list of environment variables checked.

this should fix issue #6862

2023-03-02 02:04 UTC, patrickdillon commented
/ok-to-test

Thanks for sending this in.
/cc @barbacbd

2023-03-03 13:51 UTC, barbacbd requested changes

2023-03-03 13:51 UTC, barbacbd commented on pkg/asset/installconfig/gcp/session.go
> +	authEnvs            = []string{"GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_CREDENTIALS", "GOOGLE_CLOUD_KEYFILE_JSON", "GCLOUD_KEYFILE_JSON"}
nit: This should be added to the comment in GetSession as well so users know the order that environment variables are selected.

2023-05-01 12:08 UTC, barbacbd reviewed
/lgtm

2023-08-17 15:10 UTC, barbacbd commented
/retest-required

2023-08-17 15:11 UTC, barbacbd commented
/remove-lifecycle stale

2023-08-17 15:36 UTC, barbacbd commented
/retitle OCPBUGS-17866: check GOOGLE_APPLICATION_CREDENTIALS env var

2023-08-17 16:08 UTC, r4f4 commented
/approve

2023-08-17 17:17 UTC, patrickdillon commented
/lgtm

2023-09-05 07:26 UTC, jianli-wei commented
/jira refresh

2023-09-05 07:26 UTC, jianli-wei commented
/label qe-approved

2023-09-05 19:10 UTC, barbacbd commented
/hold cancel

2023-09-06 16:21 UTC, sadasu commented
/retest-required

2023-10-10 20:23 UTC, sadasu commented
/jira refresh

2023-10-10 20:23 UTC, sadasu commented
/retest-required

2023-10-18 03:06 UTC, sadasu commented
/test e2e-gcp-ovn

2023-10-24 18:30 UTC, sadasu commented
/hold cancel

2023-10-31 15:29 UTC, patrickdillon commented
/hold cancel
/skip
/retest-required

2023-11-01 10:28 UTC, merged