Make AWS API call to GetHostedZone with a context
openshift/installer pull request #7058
Opened 2023-03-31 17:09 UTC by sadasu

This makes sure that the AWS API call to GetHostedZone would hang indefinitely.

2023-03-31 17:12 UTC, sadasu commented
/jira refresh

2023-03-31 17:20 UTC, r4f4 requested changes
When you change client API interfaces, make sure you also update the mock generated code. The unit tests also need to be fixed.

2023-03-31 17:20 UTC, r4f4 commented on pkg/asset/installconfig/aws/validation.go
> +	ctx := context.TODO()
This is an empty context that never expires [1] so this is not doing anything for the API call. We want a `context.WithTimeout()` where we specify a reasonable timeout for the call to execute and return

[1] https://pkg.go.dev/context#TODO

2023-04-04 18:42 UTC, sadasu commented
@mtulio could you make sure this fix doesn't break anything for AWS edge pools?

2023-04-04 19:41 UTC, mtulio commented
Validating feature: edge subnets / installing in existing subnets with Local Zones (https://github.com/openshift/installer/pull/6371)

- Flow `create manifests` -> `create cluster`: OK
```
$ grep 'VPC(' pkg/asset/installconfig/aws/metadata.go -A 5
func (m *Metadata) VPC(ctx context.Context) (string, error) {
	if m.vpc == "" {
		if len(m.Subnets) == 0 {
			return "", errors.New("cannot calculate VPC without configured subnets")
		}
$ ./openshift-install version
./openshift-install unreleased-master-7973-g5a071576b25c947686d2569938db79168dd935ef
built from commit 5a071576b25c947686d2569938db79168dd935ef
release image registry.ci.openshift.org/origin/release:4.13
release architecture amd64

$ cat ${INSTALL_DIR}/install-config.yaml |grep subnets -A 7
    subnets:
    - subnet-0f4a8fe9bc90d98b6
    - subnet-09f6b127d615c5609
    - subnet-06efea54043e1c84e
    - subnet-070961c54703a466a
    - subnet-0d4491d7a6d8931ad
    - subnet-03d1e337796fd51c7
    - subnet-088a8ce5bf940f109

$ OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="$RELEASE" \
>   $INSTALLER create manifests --dir $INSTALL_DIR
INFO Credentials loaded from the "openshift-dev" profile in file "/home/mtulio/.aws/credentials" 
INFO Consuming Install Config from target directory 
INFO Manifests created in: ocp-lz10-10/manifests and ocp-lz10-10/openshift 

 $ grep us-east- ocp-lz10-10/openshift/99_openshift-cluster-api_worker-machineset-3.yaml 
  name: ocp-lz10-srtgg-edge-us-east-1-iah-1a
      machine.openshift.io/cluster-api-machineset: ocp-lz10-srtgg-edge-us-east-1-iah-1a
        machine.openshift.io/cluster-api-machineset: ocp-lz10-srtgg-edge-us-east-1-iah-1a
          machine.openshift.io/zone-group: us-east-1-iah-1
            availabilityZone: us-east-1-iah-1a
            region: us-east-1

$ OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="$RELEASE"   $INSTALLER create cluster --dir $INSTALL_DIR
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.13.0-rc.0-x86_64). Please be warned, this is not advised 
INFO Consuming OpenShift Install (Manifests) from target directory 
(...)
INFO Waiting up to 20m0s (until 4:50PM) for the Kubernetes API at https://api.ocp-lz10.devcluster.openshift.com:6443... 
```

- Flow `create cluster`: OK
```
$ grep subnets -A7 ${INSTALL_DIR}/install-config.yaml
    subnets:
    - subnet-086577468fec3c450
    - subnet-0dd4798fcd7c9692a
    - subnet-046cb9c1281f77e4e
    - subnet-067771e48f0c8ba49
    - subnet-056743401e0642f40
    - subnet-0fee2d3ac858ba8ff
    - subnet-0e027a92e2706750b

$ OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="$RELEASE" $INSTALLER create cluster --dir $INSTALL_DIR
INFO Credentials loaded from the "openshift-dev" profile in file "/home/mtulio/.aws/credentials" 
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.13.0-rc.0-x86_64). Please be warned, this is not advised 
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
(...)
INFO Waiting up to 20m0s (until 4:59PM) for the Kubernetes API at https://api.ocp-lz11.devcluster.openshift.com:6443... 
INFO API v1.26.2+06e8c46 up                       
INFO Waiting up to 30m0s (until 5:11PM) for bootstrapping to complete...
```

/lgtm

2023-04-04 20:53 UTC, r4f4 commented
@sadasu it would be good for posterity to document in the commit description what the mutex problem is and how we're fixing it.

2023-04-05 05:10 UTC, zaneb commented
/retest

2023-04-05 13:26 UTC, sadasu commented
/retest-required

Current failure in e2e-aws-ovn is not related to this fix.

2023-04-06 13:37 UTC, r4f4 commented
> Hello @sadasu @mtulio, FYI, I did pre-merge test with following configuration:
> 
>     * byo PHZ, create cluster directly. PASS
> 
>     * byo PHZ, create manifests/ignition/cluster. PASS
> 
>     * Local Zone + byo PHZ, create cluster directly. PASS
> 
>     * Local Zone + byo PHZ, create manifests/ignition/cluster. PASS

@yunjiang29 that's great testing. I appreciate the comprehensive `create cluster` and `create manifests + cluster` checks. @sadasu is working on an alternative solution at https://github.com/openshift/installer/pull/7070 which is functionally similar to this PR but with code cleanups to avoid similar bugs in the future.

2023-04-06 15:07 UTC, r4f4 commented
> > an alternative solution at #7070 which is functionally similar to this PR but with code cleanups to avoid similar bugs in the future.
> 
> @r4f4, so #7070 will be the final solution, and this PR won't be merged, is it right?

I think that's the idea, but I'll leave it to @sadasu to confirm or deny.

2023-04-25 14:08 UTC, closed without merging