Add support for CPMSO for Power VS
openshift/installer pull request #7226
Opened 2023-06-02 05:13 UTC by Karthik-K-N

Add support for [CPMSO](https://github.com/openshift/cluster-control-plane-machine-set-operator) for Power VS platform, Initially it will be in Inactive state, Later based on the feedback we can by default make it active.

opesnhift/api changes PR: https://github.com/openshift/api/pull/1415
openshfit/machine-api-provider-powervs changes: https://github.com/openshift/machine-api-provider-powervs/pull/41

2023-06-02 05:14 UTC, Karthik-K-N commented
/hold 

Wait for testing and merging of https://github.com/openshift/machine-api-provider-powervs/pull/41 PR

2023-06-07 12:42 UTC, Karthik-K-N commented
/hold cancel

2023-06-07 13:19 UTC, rna-afk commented
/lgtm

2023-06-15 07:32 UTC, mkumatag requested changes

2023-06-15 07:32 UTC, mkumatag commented on pkg/asset/machines/master.go
> +		}
```suggestion
		if err := powervs.ConfigMasters(machines, controlPlaneMachineSet, clusterID.InfraID, ic.Publish); err != nil {
			return errors.Wrap(err, "failed to to configure master machine objects")
		}
```

2023-06-15 11:03 UTC, Karthik-K-N commented on pkg/asset/machines/powervs/machines.go
>  		provider, err := provider(clusterID, platform, mpool, userDataSecret, image, network)
Did you mean to move 
```
machineSetProvider = *provider
```
outside the loop? but provider is local to loop so we may need to declare it prior

2023-06-15 11:19 UTC, mkumatag commented on pkg/asset/machines/powervs/machines.go
>  		provider, err := provider(clusterID, platform, mpool, userDataSecret, image, network)
something like this:
```golang
machineSetProvider, err := provider(clusterID, platform, mpool, userDataSecret, image, network)
if err != nil {
	return nil, nil, errors.Wrap(err, "failed to create provider")
}
```

2023-06-15 13:08 UTC, Karthik-K-N commented on pkg/asset/machines/powervs/machines.go
>  		provider, err := provider(clusterID, platform, mpool, userDataSecret, image, network)
but we need to create all the machines as well https://github.com/Karthik-K-N/installer/blob/ec043c011484e4057559e6fd03b36b051fd2b7da/pkg/asset/machines/powervs/machines.go#L64-L71

2023-06-16 05:11 UTC, Karthik-K-N commented on pkg/asset/machines/powervs/machines.go
>  		provider, err := provider(clusterID, platform, mpool, userDataSecret, image, network)
Updated accordingly.

2023-06-16 05:31 UTC, mkumatag approved these changes
/lgtm
/approve

2023-07-10 04:15 UTC, Karthik-K-N commented
/retest-required

2023-07-12 06:11 UTC, Karthik-K-N commented
/retest-required

2023-07-12 06:11 UTC, Karthik-K-N commented
/retest

2023-07-12 11:28 UTC, Karthik-K-N commented
@rna-afk could you please help in merging this PR

2023-07-14 16:40 UTC, patrickdillon commented
/test ?

2023-07-14 16:52 UTC, patrickdillon reviewed
/approve

Is there a powervs sme that can review/lgtm?

2023-07-14 16:52 UTC, patrickdillon commented on pkg/asset/machines/powervs/machines.go
> +			return errors.New("Unable to set load balancers to control plane machine set")
nit: errors should start with a lowercase letter, but no need to change this unless you're making other changes

2023-07-14 16:52 UTC, patrickdillon commented on pkg/asset/machines/powervs/machines.go
> +		return errors.New("Unable to set load balancers to control plane machine set")
nit: errors should start with a lowercase letter, but no need to change this unless you're making other changes

2023-07-14 16:57 UTC, Karthik-K-N commented
> /approve
> 
> Is there a powervs sme that can review/lgtm?

Thank you, Its already been reviewed and approved from Power VS team https://github.com/openshift/installer/pull/7226#pullrequestreview-1482743421

2023-07-14 17:57 UTC, patrickdillon commented
/lgtm
based on https://github.com/openshift/installer/pull/7226#pullrequestreview-1482743421

2023-07-16 01:00 UTC, merged

2024-07-09 07:22 UTC, JoelSpeed commented
@Karthik-K-N Looks like this is still inactive by default? Any reason not to be making these active?

Also, do you intend to have upgraded clusters add CPMSs? On other platforms we have a generator in the CPMS repo itself that creates CPMSs based on the existing Machines in the cluster, in an inactive state

2024-07-09 09:10 UTC, Karthik-K-N commented
We started with inactive state thinking to have enough testing done before making it active. @juliemathew If testing looks or if there is not anything concerning, Shall I make it active by default.


Initially I thought its not required to have generator as at that time PowerVS was still in TP mode. @mkumatag do you think we need to cover this scenario as well?