AGENT-692: Update assisted-service dependencies
openshift/installer pull request #7439
Opened 2023-08-22 10:29 UTC by zaneb

Depend only on the new `github.com/openshift/assisted-service/client` go module, along with the existing `/api` and `/models` modules, and drop the dependency on the main assisted-service module. This allows us to update to the latest versions of all of these. Previously this was not possible because assisted-service now depends on the rust nmstate bindings, which we don't yet have a way to build on all platforms.

In order to drop the dependency, we have to inline the old code for shelling out to `nmstatectl`, and stop relying on some library convenience functions.

2023-08-22 21:42 UTC, rwsu requested changes

2023-08-22 21:42 UTC, rwsu commented on pkg/asset/agent/image/oc.go
> +	if err != nil {
```suggestion
	if err == nil {
```

2023-08-22 21:44 UTC, bfournie commented on pkg/asset/agent/image/oc.go
> +	if err != nil {
I think this should be:
`if err == nil {`

According to example https://pkg.go.dev/os/exec#Command

2023-08-22 21:54 UTC, bfournie commented on pkg/asset/agent/image/oc.go
> +	if err != nil {
With that change I was able to successfully install with `4.14.0-0.ci-2023-08-22-121303`

2023-08-22 22:03 UTC, bfournie commented on pkg/asset/agent/image/oc.go
> +	if err != nil {
Duplicate comments :-)

2023-08-23 07:10 UTC, andfasano commented on pkg/asset/agent/manifests/staticnetworkconfig/generator.go
> +				if nmConnection, ok := connectionElems[1].(string); ok {
Are these linter-driven changes?

2023-08-23 10:06 UTC, andfasano commented
/lgtm

2023-08-23 14:05 UTC, rwsu approved these changes
/approve

2023-08-23 14:11 UTC, merged