AGENT-889: Integration tests for add-nodes command
openshift/installer pull request #8201
Opened 2024-03-22 09:21 UTC by andfasano

(This patch is based on PR #8093, so the relevant commit is [22fafe](https://github.com/openshift/installer/commit/22fafe82792dd820d76890dcd4e73315094e4025))

This patch introduces an integration test for the `node-joiner add-nodes` command. Similarly to the already existing openshift-installer integration tests, it adopts [testscript](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript). In addition, since the command requires the presence of a cluster, it uses [envTest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) for that scope.
To properly arrange the test scenario required, all the yaml file generated by the test in the `setup` subfolder will be pre-processed and applied to the cluster before running the test.

2024-03-22 15:24 UTC, andfasano commented
Note: in order to pass, the `agent-integration-tests` job needs to use an image where capi binaries are present

2024-04-05 16:19 UTC, rwsu requested changes

2024-04-05 16:19 UTC, rwsu commented on cmd/node-joiner/nodejoiner_integration_test.go
> +			filepath.Join(build.Default.GOPATH, "pkg", "mod", "github.com", "openshift", "api@v0.0.0-20240301093301-ce10821dc999", "config", "v1"),
Was seeing:
```
[rwsu@installer]$ go test ./cmd/node-joiner/.
--- FAIL: TestNodeJoinerIntegration (0.07s)
    --- FAIL: TestNodeJoinerIntegration/add-nodes (5.58s)
        testscript.go:534: FAIL: testdata/add-nodes.txt:0: unable to install CRDs onto control plane: unable to read CRD files: stat /home/rwsu/go/pkg/mod/github.com/openshift/api@v0.0.0-20240301093301-ce10821dc999/config/v1: no such file or directory
```
If you having troubling running the new integration test, I had to do the following:
```
export OPENSHIFT_INSTALL_CLUSTER_API=YES
./hack/build.sh
go mod vendor
go mod tidy
go test ./cmd/node-joiner/.
```

2024-04-05 16:19 UTC, rwsu commented on cmd/node-joiner/testdata/add-nodes.txt
> +
Should we also assert the contents of agent-addnodes.x86_64.iso contain the correct values in /etc/assisted/manifests to add the extra-worker-0 node to the cluster?

2024-08-30 16:03 UTC, andfasano commented
/hold

2024-09-06 15:59 UTC, andfasano commented
Replaced by https://github.com/openshift/installer/pull/8976

2024-09-06 15:59 UTC, closed without merging