no-jira: Removing unused terraform variables
openshift/installer pull request #8360
Opened 2024-05-07 14:30 UTC by barbacbd

** Removed unused variables for azure from tfvars, platform specific variables, and the teraform variables file.
** Removed unused teraform variables in aws terraform variables file.
** Removed unsued variables in gcp terraform variables file.

2024-05-07 14:33 UTC, barbacbd commented
/cc @r4f4

2024-05-07 14:39 UTC, r4f4 requested changes
The variables from `data/data/azure/variables-azure.tf` regarding azurestack cannot be removed because the config file is shared by both azure and azurestack.

2024-05-07 14:39 UTC, r4f4 commented on pkg/asset/cluster/tfvars/tfvars.go
> -
I think this breaks azure stack.

2024-05-07 14:43 UTC, barbacbd commented
/hold

2024-05-07 14:48 UTC, barbacbd commented
/hold cancel

2024-05-08 10:07 UTC, r4f4 reviewed
LGTM but I don't know anything about the `*_config_version` variables. Are they some part of an idea that never took off?

It's unfortunate that `tf-fmt` is not behaving consistently: in some instances it aligns the `=` and in others it doesn't :man_shrugging:

2024-05-09 04:24 UTC, jhixson74 commented
/lgtm

2024-05-14 17:18 UTC, patrickdillon commented
> It's unfortunate that `tf-fmt` is not behaving consistently: in some instances it aligns the `=` and in others it doesn't 🤷‍♂️

I think it depends on how big the gap is. it will only align if the strings are somewhat similar in length

2024-05-14 17:19 UTC, patrickdillon commented
/approve

2024-05-14 17:19 UTC, r4f4 commented
> > It's unfortunate that `tf-fmt` is not behaving consistently: in some instances it aligns the `=` and in others it doesn't 🤷‍♂️
> 
> I think it depends on how big the gap is. it will only align if the strings are somewhat similar in length

TIL.

2024-05-14 18:01 UTC, barbacbd commented
/label acknowledge-critical-fixes-only

2024-05-15 00:45 UTC, merged