CORS-3561: Add new disk types GCP Control Plane nodes
openshift/installer pull request #8880
Opened 2024-08-20 14:18 UTC by barbacbd

** GCP Control Plane Nodes should now be allowed to use pd-balanced and hyperdisk-balanced. The IOPS rating is sufficient for both disk types to be used for control plane nodes, but pd-standard still falls short.

2024-08-20 14:19 UTC, barbacbd commented
/label platform/google

2024-08-20 22:52 UTC, rna-afk commented
/lgtm

2024-08-21 12:25 UTC, r4f4 requested changes

2024-08-21 12:25 UTC, r4f4 commented on pkg/asset/installconfig/gcp/validation.go
> +				diskTypes := sets.NewString("pd-ssd", "pd-balanced", "hyperdisk-balanced")
Let's use the non-deprecated set syntax
```suggestion
				diskTypes := sets.New("pd-ssd", "pd-balanced", "hyperdisk-balanced")
```

2024-08-21 12:25 UTC, r4f4 commented on pkg/asset/installconfig/gcp/validation.go
> +					return append(allErrs, field.NotSupported(field.NewPath("controlPlane", "platform", "gcp", "diskType"), ic.ControlPlane.Platform.GCP.DiskType, diskTypes.List()))
```suggestion
					return append(allErrs, field.NotSupported(field.NewPath("controlPlane", "platform", "gcp", "diskType"), ic.ControlPlane.Platform.GCP.DiskType, sets.List(diskTypes)))
```

2024-08-21 12:25 UTC, r4f4 commented on pkg/types/gcp/validation/machinepool.go
> +		diskTypes := sets.NewString("pd-ssd", "pd-balanced", "hyperdisk-balanced")
As mentioned above, let's not duplicate this.

2024-08-21 12:25 UTC, r4f4 commented on pkg/types/gcp/validation/machinepool.go
> +		diskTypes := sets.NewString("pd-ssd", "pd-balanced", "hyperdisk-balanced")
If we are validating the disk type during install-config validation, do we need to do it here as well?

2024-08-21 16:05 UTC, r4f4 commented
/approve

2024-08-21 16:34 UTC, sadasu commented
Will check back after golint failures are fixed.

2024-08-21 18:31 UTC, barbacbd commented
/retest

2024-08-21 19:08 UTC, pawanpinjarkar commented
/test ci/prow/unit

2024-08-21 19:08 UTC, pawanpinjarkar commented
/test unit

2024-08-22 11:30 UTC, barbacbd commented
/retest-required

2024-08-22 15:47 UTC, barbacbd commented
/retest-required

2024-08-22 16:02 UTC, r4f4 commented
/lgtm

2024-08-26 13:28 UTC, barbacbd commented
/retest-required

2024-08-26 18:47 UTC, barbacbd commented
/label acknowledge-critical-fixes-only

2024-08-26 18:49 UTC, merged