OCPBUGS-41785: Validate MTU for custom network
openshift/installer pull request #8988
Opened 2024-09-10 15:46 UTC by mandre

Set the minimum MTU to 1380 when deploying on IPv6. This value
corresponds to the minimum MTU for IPv6, which is 1280, and the
ovn-kubernetes overhead, which is 100.

2024-09-10 17:47 UTC, EmilienM commented
/lgtm
if we wanted to go deeper would would add a check for single stack v6 where the minimum MTU is actually higher :)

2024-09-10 19:57 UTC, MaysaMacedo requested changes

2024-09-10 19:57 UTC, MaysaMacedo commented on pkg/asset/installconfig/openstack/validation/platform.go
> +	minimumMTU = 1280
this should be 1280 + 100, which is OVN-K overhead

https://github.com/openshift/installer/blob/0810957e2ddd9d7fd7815b9d0d07012fe7a7a1de/docs/user/openstack/deploy_dual_stack_cluster.md?plain=1#L15

2024-09-11 12:27 UTC, MaysaMacedo commented
/lgtm
/test e2e-openstack-dualstack

2024-09-11 13:29 UTC, sadasu commented
/approve

2024-09-11 14:08 UTC, merged

2024-09-11 14:29 UTC, mandre commented
/jira backport release-4.17,release-4.16,release-4.15