OCPBUGS-44171: Validate aws userTags when supplied
openshift/installer pull request #9171
Opened 2024-11-04 20:06 UTC by barbacbd

** AWS User tags support white space as valid characters. 
** User tags should be validated every time that they are supplied not only when propagateTags is True.

2024-11-04 20:06 UTC, barbacbd commented
/cc @patrickdillon @r4f4

2024-11-04 20:07 UTC, barbacbd commented
/jira refresh

2024-11-04 20:15 UTC, r4f4 requested changes

2024-11-04 20:15 UTC, r4f4 commented on pkg/types/aws/validation/platform.go
> +		return fmt.Errorf("name key is not allowed for user defined tags")
```suggestion
		return fmt.Errorf("Name key is not allowed for user defined tags")
```
or
```suggestion
		return fmt.Errorf("\"Name\" key is not allowed for user defined tags")
```

2024-11-04 20:15 UTC, r4f4 commented on pkg/types/aws/validation/platform.go
> +var tagRegex = regexp.MustCompile(`^[0-9A-Za-z\p{Z}_.:/=+-@]*$`)
Let's change this as a follow-up, if needed.

2024-11-04 22:25 UTC, r4f4 reviewed
/lgtm

2024-11-12 15:34 UTC, barbacbd commented on pkg/types/aws/validation/platform.go
> -		} else {
No we aren't losing any validation. Its in the function. It was being checked twice.

2024-11-12 15:37 UTC, sadasu commented on pkg/types/aws/validation/platform.go
> -		} else {
Ah! I see that it is included as part of kubernetesNamespaceRegex and is not allowed as a valid UserTag. Thanks.

2024-11-12 15:37 UTC, sadasu commented
/approve

2024-11-12 18:48 UTC, merged