OCPBUGS-45932: IBMCloud: Add service overrides
openshift/installer pull request #9297
Opened 2024-12-09 22:40 UTC by cjschaef

Add additional IBM Cloud service override support for COS Config
and Global Catalog, for IBM Cloud Terraform plugin and any
Cluster Operators.

Related: https://issues.redhat.com/browse/OCPBUGS-45932
Related: https://issues.redhat.com/browse/OCPBUGS-34974

2024-12-09 22:54 UTC, cjschaef commented
I think this still requires an update to `openshift/api` first.

2024-12-13 07:56 UTC, MayXuQQ commented
/jira refresh

2024-12-13 09:40 UTC, MayXuQQ commented
pre-merge build failed https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1867487982798245888

> make: *** [Makefile:33: bin/linux_amd64/terraform-provider-ibm.zip] Error 1

2025-01-23 00:30 UTC, jhixson74 commented
/uncc

2025-02-19 10:54 UTC, MayXuQQ commented
/retest

2025-02-19 14:06 UTC, MayXuQQ requested changes
fail to build the pre-merge test

2025-03-31 15:12 UTC, cjschaef commented
Will need to review go mod bumps

2025-04-01 05:40 UTC, cjschaef commented
I will have to be careful in order to not cause a regression of https://issues.redhat.com/browse/OCPBUGS-54263, and may not be able to bump the IBM TF version from 1.61 to 1.71 like the PR currently attempts, to get a presumed fix in the IBM TF provider.

2025-06-30 09:12 UTC, MayXuQQ commented
/lifecycle frozen

2025-07-31 02:06 UTC, MayXuQQ commented
/lifecycle frozen

2025-08-30 08:00 UTC, closed without merging